### ISSUE TITLE
Anmeldung

### ISSUE THREAD

**Issue by di3t0** [TA2k/ioBroker.lg-thinq#1]
Ich habe einen Haushalt über ein Google-Konto angemeldet, aber wenn ich mein Konto im Login eingebe, logge ich mich nicht ein. Gibt es eine andere Möglichkeit?

![2021_09_21_11_02_25_Window](https://user-images.githubusercontent.com/40027237/134143458-b40c7a44-b1b3-4875-acce-9460227ae858.jpg)

**Comment by foxriver76** [comment]
Same if account is linked to an iCloud account

```
2021-11-02 13:18:18.076 | error | TypeError: Cannot read property 'account' of undefined
-- | -- | --
lg-thinq.0 | 2021-11-02 13:18:17.851 | error | {"error":{"request":"/emp/v2.0/account/session/blabla@privaterelay.appleid.com","code":"MS.001.10","message":"Already in use by 3rd-Party Registeration:APPL"}}

```

**Comment by TA2k** [comment]
Mh ein normalen Account erstellen ist keine Option?

**Comment by EddyDsSmartHome** [comment]
Hi TA2k, ist nochmal eine Änderung geplant bezüglich Google & Co. Accounts?

Gruß
Eddy

**Comment by TA2k** [comment]
Eigentlich nicht
