### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by tomtomzurich** [TA2k/ioBroker.lg-thinq#10]
Since a couple of weeks this io-broker adapter doesn't work any more.
The running instance is throwing hundreds of errors that there is something wrong either with the login or an token.
Based on the fact, that this adapter doesn't have anything to refresh a token, I guess that there is now something wrong with the login process coded. (most probably LG changed something at the login)
My credentials are definitely right, because the LG App as well as the LG web-platform works fine and the login in both cases are working as well.

![Bildschirm­foto 2022-11-03 um 20 15 33](https://user-images.githubusercontent.com/10370132/200898992-2ca5e284-14b1-4114-8056-7526f767d465.png)

**Comment by christianloesel** [comment]
Same here. After restarting the Instance I got the following messages in my log:

<html>
<body>

lg-thinq.0 | 2022-11-17 14:19:15.466 | info | Found: 0 devices
-- | -- | -- | --
lg-thinq.0 | 2022-11-17 14:19:15.465 | error | Could not receive homes. Please check your app and accept new agreements
lg-thinq.0 | 2022-11-17 14:19:15.463 | error | {"resultCode":"0110","result":""}
lg-thinq.0 | 2022-11-17 14:19:15.457 | error | Error: Request failed with status code 400
lg-thinq.0 | 2022-11-17 14:19:15.046 | info | Login successful
lg-thinq.0 | 2022-11-17 14:19:12.289 | info | starting. Version 0.0.7 in /opt/iobroker/node_modules/iobroker.lg-thinq, node: v16.17.0, js-controller: 4.0.23
lg-thinq.0 | 2022-11-17 14:19:06.420 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
lg-thinq.0 | 2022-11-17 14:19:06.417 | info | terminating
lg-thinq.0 | 2022-11-17 14:19:06.415 | info | Got terminate signal TERMINATE_YOURSELF
lg-thinq.0 | 2022-11-17 14:18:46.701 | info | Try to refresh Token
lg-thinq.0 | 2022-11-17 14:18:46.701 | error | {"resultCode":"0110","result":""}
lg-thinq.0 | 2022-11-17 14:18:46.700 | error | Error: Request failed with status code 400
lg-thinq.0 | 2022-11-17 14:18:46.700 | error | Failed to get home

</body>
</html>

As mentioned I opned the LG ThinQ App and got asked to agree new Terms. After accepting those, I restarted the Instance in ioBroker again and it worked again.

**Comment by Lucky-ESA** [comment]
This is not an adapter error
