### ISSUE TITLE
v0.1.0 Crashes 

### ISSUE THREAD

**Issue by Sineos** [TA2k/ioBroker.lg-thinq#12]
**Describe the bug**  
<html><body>

host.smartvm | 2022-11-16 07:54:12.981 | error | instance system.adapter.lg-thinq.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.smartvm | 2022-11-16 07:54:12.981 | error | Caught by controller[1]:     at LgThinq.onReady (/opt/iobroker/node_modules/iobroker.lg-thinq/main.js:146:57)
host.smartvm | 2022-11-16 07:54:12.981 | error | Caught by controller[1]:     at LgThinq.getDeviceModelInfo (/opt/iobroker/node_modules/iobroker.lg-thinq/main.js:648:32)
host.smartvm | 2022-11-16 07:54:12.981 | error | Caught by controller[1]:     at Function.keys (<anonymous>)
host.smartvm | 2022-11-16 07:54:12.981 | error | Caught by controller[1]: TypeError: Cannot convert undefined or null to object
host.smartvm | 2022-11-16 07:54:12.981 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
lg-thinq.0 | 2022-11-16 07:54:12.432 | error | Cannot convert undefined or null to object
lg-thinq.0 | 2022-11-16 07:54:12.431 | error | TypeError:  Cannot convert undefined or null to object    at Function.keys  (<anonymous>)    at LgThinq.getDeviceModelInfo  (/opt/iobroker/node_modules/iobroker.lg-thinq/main.js:648:32)    at  LgThinq.onReady  (/opt/iobroker/node_modules/iobroker.lg-thinq/main.js:146:57)
lg-thinq.0 | 2022-11-16 07:54:12.430 | error | unhandled promise rejection: Cannot convert undefined or null to object
lg-thinq.0 | 2022-11-16 07:54:12.429 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

</body>
</html>

**To Reproduce**  
Crashes right after start

**Versions:**  
 - Adapter version: 0.1.0
 - JS-Controller version: 4.0.23
 - Node version: v16.18.1
 - Operating system:  Ubuntu 22.04.1 LTS

**Comment by Lucky-ESA** [comment]
What is the content of the following data points?
lg-thinq.0.xxx.deviceType
lg-thinq.0.xxx.platformType

**Comment by Sineos** [comment]
Fixed in current git. Many thanks
