### ISSUE TITLE
[FR] JSON Mapping

### ISSUE THREAD

**Issue by Sineos** [TA2k/ioBroker.lg-thinq#14]
Is there a way to map the JSON states, e.g. according to 

`lg-thinq.0.c1856540-b473-11ec-8134-203dbd358e3b.modelJsonUri`
https://eic.lgthinq.com:46030/api/webContents/modelJSON?modelName=F1K2CSV2T_FR_WIFI&countryCode=WW&contentsId=JS0418081409435415&authKey=thinq

and

`lg-thinq.0.c1856540-b473-11ec-8134-203dbd358e3b.langPackModelUri`
https://eic.lgthinq.com:46030/api/webContents/moduleDownload?type=langPack/MP/F1K2CSV2T_FR_WIFI/MP_WM_F1K2CSV2T_FR_WIFI_LANG_DE-WW_VER_7.0.json&fileName=MP_WM_F1K2CSV2T_FR_WIFI_LANG_DE-WW_VER_7.0&authKey=thinq

**Comment by Lucky-ESA** [comment]
Das passt aber nur zu ca. 70%

**Comment by Sineos** [comment]
Ich würde es auch manuell mappen und einen PR schicken, wenn du mir sagst wo das passieren muss. Im Moment zeigt unsere WaMa halt nur `WM_STATE_END_W` o.ä. an

**Comment by Lucky-ESA** [comment]
Lade mal vom GIT und schau was alles ersetzt wird.

**Comment by Lucky-ESA** [comment]
mapping in 0.1.1 done
