### ISSUE TITLE
Log Meldungen

### ISSUE THREAD

**Issue by Instanz1** [TA2k/ioBroker.lg-thinq#18]
Nachdem ich den ioBroker neu aufsetzen musste habe ich heute meinen Trockner gestartet und jetzt haut er mir die Log voll mit diesen Meldungen:

`<html><body>

lg-thinq.0 | 2022-11-20 17:48:22.627 | info | mqtt closed
-- | -- | -- | --
lg-thinq.0 | 2022-11-20 17:48:22.441 | info | MQTT reconnect
lg-thinq.0 | 2022-11-20 17:47:41.269 | warn | State  value to set for  "lg-thinq.0.70d547b5-5572-1b10-865b-402f8665e755.snapshot.washerDryer.dnn_temp"  has value "-1" less than min "0"
lg-thinq.0 | 2022-11-20 16:46:41.163 | warn | State  value to set for  "lg-thinq.0.70d547b5-5572-1b10-865b-402f8665e755.snapshot.washerDryer.dnn_temp"  has value "-1" less than min "0"

</body>
</html>`

**Comment by Lucky-ESA** [comment]
Das ist einer der 5 Datenpunkte die ich manuell angehen musste. Der Fehler ist nach dem ersten Start weg. Du kannst den Raw vom Datenpunkt ändern von "min": 0, in "min": -1
Werde das im Adapter ändern. Die States ändern sich allerdings wieder nach einem Neustart.
