### ISSUE TITLE
ActiveSavingStatus Warning greater than 3

### ISSUE THREAD

**Issue by manny4566** [TA2k/ioBroker.lg-thinq#24]
Hi,
alle x Stunden tauchen im Log folgende Fehler auf bei mir:

`State  value to set for  "lg-thinq.0.XXXX.ActiveSavingStatus"  has value "255" greater than max "3"`

Es handelt sich bei dem Gerät um einen Kühlschrank, der den Wert 255 zurück liefert bei dem Objekt.
Scheinbar ist das  in dem Fall normal. Kann die Abfrage abgeändert werden, dass  kein Warning kommt bei einem Wert bis 255? :)
Danke

**Comment by TA2k** [comment]
kannst du mal schauen ob es was bringt 
lg-thinq.0.XXXX.ActiveSavingStatus
zu löschen und adapter neustarten

**Comment by Lucky-ESA** [comment]
Habe diesen Datenpunkt nicht. Kannst du den Inhalt von lg-thinq.0.xxxx.modelJsonUri mal hier posten.

**Comment by manny4566** [comment]
> kannst du mal schauen ob es was bringt lg-thinq.0.XXXX.ActiveSavingStatus zu löschen und adapter neustarten

Kein Erfolg. Das Objekt wird neu angelegt mit der 255.

**Comment by manny4566** [comment]
> Habe diesen Datenpunkt nicht. Kannst du den Inhalt von lg-thinq.0.xxxx.modelJsonUri mal hier posten.

[modelJsonUri](https://eic.lgthinq.com:46030/api/webContents/modelJSON?modelName=2RES1VE61PFWA&countryCode=WW&contentsId=JS0308233842155581&authKey=thinq)

**Comment by Lucky-ESA** [comment]
Bitte vom Git laden.

**Comment by manny4566** [comment]
Danke. Ging ja super schnell

**Comment by TA2k** [comment]
@Lucky-ESA macht e sivelleicht sinn generisch den default als max zu nehmen wenn default>max ist?

**Comment by Lucky-ESA** [comment]
Es gibt leider zu viele unterschiedliche default Werte was ich immer prüfen müsste. Des Weiteren gibt es auch viele Werte ohne default oder Texte.

**Comment by TA2k** [comment]
Aber du checkst doch eh auf 
if (deviceModel["MonitoringValue"][state]["valueMapping"].max)
da kann man doch auch schauen ob if (deviceModel["MonitoringValue"][state]["valueMapping"].default vorhanden und größer als max is und das nehmen

**Comment by Lucky-ESA** [comment]
Habedefault bereits schon in einer Variable und kurz die Abfrage geändert.
