### ISSUE TITLE
 AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by manny4566** [TA2k/ioBroker.lg-thinq#27]
Hi, hat sich eventuell etwas an der LG Api geändert ?
Bekomme neuerdings Fehler im Log nach dem Login des Adapters:

```
lg-thinq.0 | 2023-07-10 23:01:36.886 | error | {"resultCode":"0110","result":""}
lg-thinq.0 | 2023-07-10 23:01:36.886 | error | AxiosError: Request failed with status code 400
lg-thinq.0 | 2023-07-10 23:01:36.258 | info | Login successful
lg-thinq.0 | 2023-07-10 23:01:34.659 | info | starting.  Version 0.1.4 (non-npm: TA2k/ioBroker.lg-thinq) in  /opt/iobroker/node_modules/iobroker.lg-thinq, node: v18.16.1,  js-controller: 4.0.24
```

Danke

**Comment by seek1338** [comment]
hab auch das gleiche Problem, wollte es nur bestätigen.

**Comment by Lucky-ESA** [comment]
Entwerder vom GIT laden oder in der APP die neuen Bedingungen bestätigen.

Gruß//Lucky

**Comment by danielthoene** [comment]
Moin!
Bei mir seit gestern wieder
`Send failed`
und
`AxiosError: Request failed with status code 400`...

v0.1.4, v0.2.0 und v0.3.0 (über GIT) erzeugen alle den Fehler. (habe jeweils immer Instanz und Adapter gelöscht; entsprechende Adapterversion installiert; Instanz erzeugt; konfiguriert)

Die Daten der Geräte (Waschmaschine und Luft-Wärme-Pumpe) werden korrekt ausgelesen. "Nur" schreiben funktioniert nicht...

Gruß,
Daniel
