### ISSUE TITLE
Adaptor needs manual restart to work

### ISSUE THREAD

**Issue by s31teg** [TA2k/ioBroker.lg-thinq#30]
**Describe the bug**  
when the adaptor is started then everything is ok. Then after some period then it stops working and reporting the data correctly in objects. the adaptor instant shows healthy and nothing I can see in the log

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.14
 - JS-Controller version: Node.js: v19.8.1
 - Node version: NPM: 9.5.1
 - Operating system: loxberry/pi

Let me know what else you need to help with this

**Comment by Lucky-ESA** [comment]
Which device?
I need the content of the following datapoints:
lg-thinq.0.xxx.deviceType
lg-thinq.0.xxx.platformType

**Comment by s31teg** [comment]
lg-thinq.0.202.deviceType
lg-thinq.0.thinq2.platformType

Is this the info you want? It's a LG V11 FDV1109W

**Comment by s31teg** [comment]
Actually, I have something in the log eventually. Is this what you need

2023-08-03 00:21:44.881  - [31merror[39m: lg-thinq.0 (15077) Failed to get home
2023-08-03 00:21:44.881  - [31merror[39m: lg-thinq.0 (15077) AxiosError: Request failed with status code 400
2023-08-03 00:21:44.882  - [31merror[39m: lg-thinq.0 (15077) {"resultCode":"0102","result":""}
2023-08-03 00:21:44.882  - [32minfo[39m: lg-thinq.0 (15077) Try to refresh Token

[iobroker.2023-08-03.log.gz](https://github.com/TA2k/ioBroker.lg-thinq/files/12259866/iobroker.2023-08-03.log.gz)

**Comment by s31teg** [comment]
It can't be. It works fine if I restart the adaptor?

**Comment by s31teg** [comment]
Emailed :)

**Comment by Lucky-ESA** [comment]
What did you enter in the instance config under Country and Language?
Your token cannot be updated....

**Comment by s31teg** [comment]
I sent you this info and query in the email. What should they be?

**Comment by s31teg** [comment]
After a bit of googling, it seems to be working and the following needs to be correct depends where your account is registered so for UK users:

Country: GB
Language: en_US

The API docs I could not see defined accepted valuves apart from the Country needs to be the ISO reference and languages I got from here: https://github.com/datasets/language-codes/blob/master/data/ietf-language-tags.csv

**Comment by Lucky-ESA** [comment]
Thanks for this information.
