### ISSUE TITLE
AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by danielthoene** [TA2k/ioBroker.lg-thinq#33]
Moin!
Bei mir seit gestern wieder
`Send failed`
und
`AxiosError: Request failed with status code 400`

Die Tips aus dem letzten Issue #27 habe ich ohne Erfolg befolgt... 

v0.1.4, v0.2.0 und v0.3.0 erzeugen alle den Fehler. (habe jeweils immer Instanz und Adapter gelöscht; entsprechende Adapterversion installiert; Instanz erzeugt; konfiguriert)

Die Daten der Geräte (Waschmaschine und Luft-Wärme-Pumpe) werden korrekt ausgelesen. "Nur" schreiben funktioniert nicht...

Gruß,
Daniel

**Comment by Lucky-ESA** [comment]
Welche Datenpunkte verwendest du zum schreiben?

**Comment by danielthoene** [comment]
Ich wollte - wie in der Vergangenheit auch - die Datenpunkte
`lg-thinq.0.d521e626-91f8-1b94-b98f-7087a701a519:10.snapshot.airState.tempState.target` ("Vorlauftemperatur")
`lg-thinq.0.d521e626-91f8-1b94-b98f-7087a701a519:10.snapshot.airState.operation` ("Heizung an/aus")
`lg-thinq.0.d521e626-91f8-1b94-b98f-7087a701a519:10.snapshot.airState.miscFuncState.silentAWHP` ("Leistungsbegrenzung an/aus")
`lg-thinq.0.d521e626-91f8-1b94-b98f-7087a701a519:10.snapshot.airState.miscFuncState.hotWater` ("Heißwasser an/aus")
schreiben.

Jetzt bin ich aber auf die Suche gegangen und habe unter `lg-thinq.0.d521e626-91f8-1b94-b98f-7087a701a519:10.remote.basicCtrl` beschreibbare Datenpunkte gefunden, mit denen ich zumindest "Vorlauftemperatur" und "Heizung an/aus" steuern kann.

Für diesen Denkanstoß schonmal Danke! :-)

**Comment by Lucky-ESA** [comment]
Wenn Datenpunkte fehlen benötige ich deine Zugangsdaten. Ohne Hardware kann ich leider nichts neu hinzufügen. Wenn du das haben möchtest dann ändere dein Passwort und sende mir deine Daten an github@luckyskills.de und wir sollten dann [hier](https://forum.iobroker.net/topic/46498/test-adapter-lg-thinq-v0-0-1/402?_=1702816710045) weitermachen.

Gruß//Lucky

**Comment by Lucky-ESA** [comment]
Oder mal eine andere Frage. Hast du den Datenpunkt lg-thinq.0.xxx.remote.sendJSON ? Wir könnten dann auch damit mal testen welcher Befehl gesendet werden muss.

**Comment by smooth036** [comment]
Hallo,

seit dem Update seitens LG am 1.4.24 (Meldungin der App das Service nicht erreichbar ist) kann ich keine Befehle mehr senden.
-Error = send failed
-error = AxiosError: Request failed with status code 400

LG WH20S Brauchwasserwärmepumpe , Daten lesen funktiert . Was sich seit dem noch geändert hat ist der Datenpunkt welcher den Betriebsmodus anzeigt ,da standen vorher die Betriebsarten jetzt nur noch Zahlen....

Ist das Problem bekannt ?

Gruß

**Comment by smooth036** [comment]
Logfile ist raus. Habe gerade festgestellt das es im Edge Browser funktiert. Lediglich unter Morzilla Firefox geht nicht !? Im Edge werden auch die Modi (Auto;Wärmepumpe;Turbo..usw) richtig angezeigt.

**Comment by Lucky-ESA** [comment]
Dann musst du mal schauen ob du alle Adapter aktuell hast. Wichtig wäre der admin Adapter. Habe mit Firefox auch nucr Probleme aber seit dem letzten Admin Update geht es wieder.

**Comment by Lucky-ESA** [comment]
closed
