### ISSUE TITLE
Absturz V3.0

### ISSUE THREAD

**Issue by Instanz1** [TA2k/ioBroker.lg-thinq#35]
Hallo,
nachdem Update heute stürzt der LG Adapter ab.

Aktuelle Version

Log wurde per E-Mail schon geschickt.

Was habe ich bisher gemacht:

Adapter deinstalliert und hier aus Github neu geladen.

**Comment by Lucky-ESA** [comment]
Danke fürs Logfile. Kannst du bitte erneut vom GIT laden. Leider habe ich keine thinq1 Geräte und muss daher immer ein wenig raten. Kommen weitere Fehler dann bitte erneut mir das Log zusenden.

Gruß//Lucky

**Comment by Lucky-ESA** [comment]
Fix with release 0.3.1
