### ISSUE TITLE
Absturz bei V0.3.1

### ISSUE THREAD

**Issue by fornax76-git** [TA2k/ioBroker.lg-thinq#38]
**Describe the bug**  
Adapter stürzt ab und wird vom iobroker deaktiviert
Nach Start des Adapters ist zunächst kein Problem zu erkennen.
Sobald das Gerät (Waschmaschine) in Betrieb ist, stürzt der Adapter ab.

**Screenshots & Logfiles**  
[iob_lgThinQ.log](https://github.com/TA2k/ioBroker.lg-thinq/files/13860577/iob_lgThinQ.log)

**Versions:**  
 - Adapter  0.3.1
 - JS-Controller version: 5.0.17
 - Node version: 18.19.0
 - Operating system: Debian 12

**Comment by Lucky-ESA** [comment]
Wurde schon gemeldet. Kannst du vielleicht mal vom GIT laden und testen?

**Comment by Lucky-ESA** [comment]
fixed with 0.3.3
