### ISSUE TITLE
Solltemperatur Wärmepumpe lässt sich nach Update auf 0.3.1 nicht mehr schreiben

### ISSUE THREAD

**Issue by EDVSpezi** [TA2k/ioBroker.lg-thinq#39]
Ich steuere seit 6 Monaten eine LG Brauchwasserwärmepumpe LG WH20S über ein Blockly-Skript. Das funktionierte bis zum Update auf die Version 0.3.1 wesentlich besser als die integrierte Zeitsteuerung der BWWP. Die Zeitsteuerung schaltet die BWWP komplett ein oder aus. Mit dem Skript konnte ich zu unterschiedlichen Tageszeiten die entsprechenden Zieltemperaturen über die Variable airState.tempState.hotWaterTarget steuern. Aktuell scheint die Variable nur noch lesbar zu sein. Ich habe das Skript deaktiviert. Wenn ich nun den Wert manuell unter "Objekte" ändere, wird er kurz danach mit dem eingestellten Wert aktualisiert.

**Comment by Lucky-ESA** [comment]
Eigentlich habe ich da nichts verändert. Bei dir sollte der Datenpunkt nun auch unter remote.XXXXX vorhanden sein.

**Comment by Lucky-ESA** [comment]
Was steht denn in diesen Datenpunkten?
lg-thinq.0.xxx.deviceType
lg-thinq.0.xxx.platformType

**Comment by Lucky-ESA** [comment]
Du kannst [hier](https://github.com/TA2k/ioBroker.lg-thinq/blob/master/docs/de/README.mdl) eine Beschreibung über dein Device erlesen.

**Comment by Lucky-ESA** [comment]
closed

**Comment by EDVSpezi** [comment]
kann ich leider nicht. ABer wie geschrieben: Problem gelöst.

![image](https://github.com/TA2k/ioBroker.lg-thinq/assets/135446535/1c0a7c82-0290-4d81-9897-a8eb3d6447ec)

**Comment by Lucky-ESA** [comment]
[Upps, ein Buchstabe zu viel](https://github.com/TA2k/ioBroker.lg-thinq/blob/master/docs/de/README.md)

**Comment by EDVSpezi** [comment]
Stimmt - nochmals danke!
