### ISSUE TITLE
Set Clean-Mode and Energy-Saving

### ISSUE THREAD

**Issue by Chrone86** [TA2k/ioBroker.lg-thinq#43]
With the LG ThinQ App for my LG airconditioner i got the possibility to set an air cleaning mode and boost mode.

![image](https://github.com/TA2k/ioBroker.lg-thinq/assets/42892237/6dcb4ef8-003e-411d-834e-202081e4aa79)

Is there a way to set those options with this adapter?

**Comment by Lucky-ESA** [comment]
What value do these data points?
lg-thinq.0.xxx.deviceType
lg-thinq.0.xxx.platformType
lg-thinq.0.xxx.modelJsonUri

**Comment by Chrone86** [comment]
deviceType: 401
platformType: thinq2
modelJsonUri: https://objectcontent.lgthinq.com/dff85143-6ba4-45c2-87fc-0fdfa3556866?hdnts=exp=1769135652~hmac=000bb8bbeda45839dc85fe64815086b666fac2c503e2d1355cb55f27aa23689f

**Comment by Lucky-ESA** [comment]
Hast du den Datenpunkt .remote.wModeCtrl.airClean ?

**Comment by Chrone86** [comment]
Nein

![image](https://github.com/TA2k/ioBroker.lg-thinq/assets/42892237/35daa556-6c8d-411c-b38f-259d6c5aae07)

**Comment by Chrone86** [comment]
Nein, lediglich unter Snapshot aber nicht unter Remote

![image](https://github.com/TA2k/ioBroker.lg-thinq/assets/42892237/5e558e73-0deb-4a77-be92-99670712606b)

**Comment by Lucky-ESA** [comment]
Kannst du mal die 3 Switch in der APP aktivieren und schauen welcher Datenpunkt sich unter Snapshot ändert?

**Comment by Chrone86** [comment]
Reinigen: lg-thinq..snapshot.airState.wMode.airClean = AC_MAIN_AIRCLEAN_ON_W / AC_MAIN_AIRCLEAN_OFF_W
Energiesparen (Kann ich bereits steuern): lg-thinq..airState.powerSave.basic = ON(1) / OFF(0)
Düse: lg-thinq..snapshot.airState.wMode.jet = COOL_JET(1) / OFF (0)

**Comment by Lucky-ESA** [comment]
Schreibe mal bitte das in den .remote.sendJSON
`{"ctrlKey": "wModeCtrl", "command": "Set", "dataKey": "airState.wMode.airClean", "dataValue": 1, "dataSetList": null, "dataGetList": null}`

Oder für aus:
`{"ctrlKey": "wModeCtrl", "command": "Set", "dataKey": "airState.wMode.airClean", "dataValue": 0, "dataSetList": null, "dataGetList": null}`

Funktioniert das?

**Comment by Chrone86** [comment]
Ja, dies klappt.

Für die Düse klappt dies ebenfalls mit folgendem JSON

{
  "ctrlKey": "wModeCtrl",
  "command": "Set",
  "dataSetList": {
    "airState.wMode.jet": 1
  },
  "dataGetList": null
}

und für aus:
{
  "ctrlKey": "wModeCtrl",
  "command": "Set",
  "dataSetList": {
    "airState.wMode.jet": 0
  },
  "dataGetList": null
}

**Comment by Lucky-ESA** [comment]
OK, dann muss ich mir jetzt überlegen wie ich das implementiere. Funktioniert eventuelle von den noch was.
```
"airState.wMode.flowForest": 0 oder 1
"airState.wMode.flowLongPower": 0 oder 1
"airState.wMode.flowShower": 0 oder 1
"airState.wMode.iceValley": 0 oder 1
"airState.wMode.turbo": 0 oder 1
"airState.wMode.jet": geht
"airState.wMode.humanCare": 0, 1 oder 2,
"airState.wMode.lowHeating": 0 oder 1
"airState.wMode.airClean": geht
"airState.wMode.smartCare": 0 oder 1
"airState.wMode.indirectWind": 0 oder 1
```

**Comment by Chrone86** [comment]
"airState.wMode.flowForest": 0 oder 1 -> Klima nimmt Befehl an, sehe aber nicht was ändert. -> Lüftergeschwindigkeit geht auf Hoch
"airState.wMode.flowLongPower": 0 oder 1 ->  Klima nimmt Befehl an, sehe aber nicht was ändert. -> Lüftergeschwindigkeit geht auf Hoch
"airState.wMode.flowShower": 0 oder 1 -> Klima nimmt Befehl an, sehe aber nicht was ändert. -> Lüftergeschwindigkeit geht auf Hoch
"airState.wMode.iceValley": 0 oder 1 ->Klima nimmt Befehl an, sehe aber nicht was ändert.
"airState.wMode.turbo": 0 oder 1 -> Klima nimmt Befehl an, sehe aber nicht was ändert.
"airState.wMode.jet": geht
"airState.wMode.humanCare": 0, 1 oder 2,  -> Klima nimmt Befehl an, sehe aber nicht was ändert.
"airState.wMode.lowHeating": 0 oder 1   -> Klima nimmt Befehl an, sehe aber nicht was ändert.
"airState.wMode.airClean": geht
"airState.wMode.smartCare": 0 oder 1  -> Klima nimmt Befehl an, sehe aber nicht was ändert.
"airState.wMode.indirectWind": 0 oder 1  -> Klima nimmt Befehl an, sehe aber nicht was ändert.

Mit Klima nimmt den Befehl an, meine ich, die Klima piepst nach dem senden des JSON. Leider bildet die App die Befehle nicht ab

**Comment by Lucky-ESA** [comment]
OK, leider habe ich keine Hardware daher musst du mal vom GIT laden und testen.

**Comment by Chrone86** [comment]
Klappt leider nicht. 
airClean sowie jet reagieren nicht. Die Klima bestätigt die gesetzten Werte nicht

**Comment by Lucky-ESA** [comment]
Werden denn die Datenpunkte unter remote angelegt?
,remote.wModeCtrl.airClean
,remote.wModeCtrl.jet

Notfalls mal auf debug stellen und mir das Log an github@luckyskills.de zusenden.

**Comment by Chrone86** [comment]
Ich muss meine Aussage korrigieren. Es funktioniert einwandfrei.
Musse den Wert jedoch via API setzen und nicht wie folgt direkt im UI: 
![image](https://github.com/TA2k/ioBroker.lg-thinq/assets/42892237/3cb2fd3a-f766-487c-8987-02bd7e6bb561)

Dann funktionieren airClean wie auch jet 

Danke für die Hilfe

**Comment by Lucky-ESA** [comment]
closed
