### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by hmersch** [TA2k/ioBroker.lg-thinq#48]
using adapte 1.0.1 (from GitHub) I get those error messages since a couple of days (not sure since when)
Any idea? Could I provide more info? Am I the only one? 
```
lg-thinq.0 | 2024-07-08 20:59:53.259 | warn | Missing Session Infos!
lg-thinq.0 | 2024-07-08 20:59:53.258 | error | Error: unable to get local issuer certificate

```

**Comment by Lucky-ESA** [comment]
Your instance settings appear to be incrorrect.
See [documention](https://github.com/TA2k/ioBroker.lg-thinq/blob/master/docs/de/README.md#instanz-einstellung-lg-thinq)

**Comment by sargonphin** [comment]
can you restart the adapter with debug? it should provide more info

**Comment by hmersch** [comment]
Yes, here we go (hopefully no secret is inside?) 


`
lg-thinq.0 | 2024-07-14 14:40:34.435 | warn | Missing Session Infos!
-- | -- | -- | --
lg-thinq.0 | 2024-07-14 14:40:34.434 | error | Error: unable to get local issuer certificate
lg-thinq.0 | 2024-07-14 14:40:27.824 | debug | {"countryCode":"DE","languageCode":"en-DE","thinq1Uri":"https://eic.lgthinq.com:46030/api","thinq2Uri":"https://eic-service.lgthinq.com:46030/v1","empUri":"https://de.m.lgaccount.com","empSpxUri":"https://de.m.lgaccount.com/spx","rtiUri":"eic.lgthinq.com:47878","mediaUri":"eic-media.lgthinq.com:47800","appLatestVer":"5.0.24121","appUpdateYn":"N","appLink":"market://details?id=com.lgeha.nuts","nestSupportAppVer":"","uuidLoginYn":"N","lineLoginYn":"N","lineChannelId":"","cicTel":"01806-115411","cicUri":"","isSupportVideoYn":"N","countryLangDescription":"Germany/English","empTermsUri":"https://de.emp.lgsmartplatform.com","googleAssistantUri":"https://assistant.google.com/services/invoke/uid/000000d26892b8a3","smartWorldUri":"","racUri":"de.rac.lgeapi.com","cssUri":"https://eic-common.lgthinq.com","cssWebUri":"http://s3-an2-op-t20-css-web-resource.s3-website.ap-northeast-2.amazonaws.com","iotssUri":"https://eic-iotservice.lgthinq.com","chatBotUri":"","autoOrderSetUri":"","autoOrderManageUri":"","aiShoppingUri":"","onestopCall":"08004544445","onestopEngineerUri":"https://svcthinq.com/global/repairRequest.html","hdssUri":"https://eic-hdss.lgthinq.com:47040","amazonDrsYn":"N","features":{"wifiScanDelay":"3000","supportTvIoTServerYn":"Y","nonProductThemes":"GIF,FOM","nonWifiQrSupportYn":"Y","shareAccountYn":"Y","androidAutoYn":"Y","newFrontReEULAYn":"Y","searchYn":"Y","thinqFaq":"Y","thinqQuickguide":"N","multiProfile":"Y","eventAutoScrollYn":"Y","supportBleYn":"Y","tvWidgetYn":"Y","pccPushProd":"101,102,103,201,202,203,204,222,301,302,303,401,402,501,504","pccWarrantyProd2":"101,102,103,104,105,106,201,202,203,204,206,222,223,301,302,303,304,401,402,403,405,406,407,408,409,410,501,504,601,603,10000,20408,30101,30102,50402,90000","thinqCss":"Y","pccRegisterProd":"101,102,103,104,105,106,201,202,203,204,222,223,301,302,303,304,401,402,403,405,406,407,408,409,410,501,504,601,603,20408,30101,30102","eventCardYn":"Y","tvRcmdContentYn":"Y","deviceSuggestionLevel":"3","awhpWidgetFeatureYn":"Y","pccMyPageYn":"Y","reportTabYn":"Y","tvFeatureYn":"Y","ewBannerYn":"Y","thinqNotice":"Y","inAppReviewYn":"Y","pccNoticeAgreement":"N","cicSupport":"Y","pccReceiptRegister":"Y","qrRegisterYn":"Y","regiHapticfeedback":"Y","tvCastYn":"Y","bleConfirmYn":"Y","personalSettingImprovementYn":"Y","awhpWidgetYn":"N","qnaSatisYn":"Y","shortcutPromotionYn":"Y","energyMonitoringYn":"Y","updateTermsTimeout":"10000","groupControlYn":"Y","supportQRPlaceGuideYn":"Y","wifiInfoFeature":"Y","pccWarrantyProd":"101,102,103,104,105,106,201,202,203,204,222,223,301,302,303,304,401,402,403,405,406,407,408,409,410,501,504,601,603,20408,30101,30102","takeATourSupport":"Y","empFrontProfileYn":"Y","disableWeatherCard":"N","pccRegAPIVer":"2","pccModelCategory":"N","supportProductManualYn":"N","apiServerTimeoutSeconds":"60","pccPush":"Y","pccRegisterProd2":"101,102,103,104,105,106,201,202,203,204,206,222,223,301,302,303,304,401,402,403,405,406,407,408,409,410,501,504,601,603,10000,20408,30101,30102,50402,90000","clientDbYn":"Y","pccWarranty":"Y","thinqCareIntegratedSD":"Y","availableTPM":"registration,onboard,search","wifiScanPolicyForSoftAp":"default","energyUsageSection":"0,5,10,15,25,35,50,100,300","dmpCollectingYn":"N","uxUpdatePopupYn":"N","smartScanWineHelpYn":"Y","pccWarrantyPeriodType":"M","closeAppDelayTimeSec":"1"},"serviceCards":[],"uris":{"ItssUri":"https://eic-it-service.lgthinq.com","amazonAlexaLearnMoreUri":"https://www.amazon.de/b?node=26247094031","takeATourUri":"https://s3-eu1-op-t20-css-contents.s3.eu-west-1.amazonaws.com/workexperience-new/ios/no-version/index.html","globalObsUrl":"https://www.lg.com/de?utm_source=thinqapp&utm_medium=outlink&utm_campaign=2022HQ-SmartTV_DE","empBackendBaseUri":"https://de.emp.lgsmartplatform.com/","onboardUri":"https://thinq-onboard-dashboard.lgthinq.com","lmpOAuthUri":"https://de.thinq.lid.lge.com","temsUri":"https://eic.energy.lgthinq.com/","careSmartDiagUri":"https://eic-hcss.lgthinq.com:47040","hdssUri":"https://eic-hdss.lgthinq.com:47040","serviceDownloadUri":"https://service-download.lgthinq.com","careSdsUri":"https://eic-hcss.lgthinq.com:47040","empFrontBaseUri2":"https://de.lgemembers.com/lgacc/service/v1/","ewGuideUri":"https://gscs.lge.com/gscs/collpack/contents/readChatbotContents.do?contentsId=20153803877030","gscsUri":"https://gscs-eu.lge.com","ewPremiumCareUrlOutlink":"https://www.service-lg.com/lg/Welcome?l=de-DE","empFrontBaseUri":"","amazonDartUri":"https://shs.lgthinq.com"}}
lg-thinq.0 | 2024-07-14 14:40:22.233 | debug | de
lg-thinq.0 | 2024-07-14 14:40:22.170 | silly | States system redis pmessage system.adapter.lg-thinq.0.logLevel/system.adapter.lg-thinq.0.logLevel:{"val":"silly","ack":true,"ts":1720960822162,"q":0,"from":"system.adapter.lg-thinq.0","lc":1720960785771}
lg-thinq.0 | 2024-07-14 14:40:22.147 | info | starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.lg-thinq, node: v18.20.3, js-controller: 5.0.19

`

**Comment by Lucky-ESA** [comment]
Ist schon komisch...Hast du Sonderzeichen in deinem Passwort? Hast du dich über en registriert?

Gruß//Lucky

**Comment by hmersch** [comment]
Hallo
Eigentlich keine wirklich aussergewöhnlichen Sonderzeichen, nein. Nen ! und nen paar Zahlen... 
Nun ist er -- nach den Wochen -- wieder grün und scheint auch zu funktionieren - Sehr Merwkürdig.

**Comment by Lucky-ESA** [comment]
Ja, sehr merkwürdig...Vielleicht war es wirklich ein Problem auf der LG Seite.
Schön das es nun funktioniert.

Gruß//Lucky
