### ISSUE TITLE
Modellerkennung LG Therma V unvollständig; kein Schreiben von Werten möglich

### ISSUE THREAD

**Issue by ArminMertes** [TA2k/ioBroker.lg-thinq#57]
Hallo,
ich komme eigentlich aus der Node-Red-Welt; habe aber aufgrund der viel breiteren Geräteunterstützung jetzt iobroker als Datenquelle ergänzt. Die Anbindung meiner LG Wärmepumpe AWHP_019101_WW (das ist eine LG Monobloc R290 16KW Therma V in Verbdinung mit dem LG Cloud Connect Gateway) läuft aber leider nur in eine Richtung.
Das Auslesen der Daten funktioniert gut und stabil.

Schreiben (z.B.  hotWaterTarget) verursacht eine Fehlermeldung
```
lg-thinq.0 | 2024-10-05 15:21:59.655 | error | AxiosError: Request failed with status code 400
lg-thinq.0 | 2024-10-05 15:21:59.655 | error | Send failed
```

Beim Start des Adapters mit eingeschaltetem Debug kommt eine Fehlermeldung "**deviceModel type** not found".
```
lg-thinq.0 | 2024-10-05 15:24:48.654 | debug | null
lg-thinq.0 | 2024-10-05 15:24:48.653 | debug | deviceModel.type not found
lg-thinq.0 | 2024-10-05 15:24:48.631 | debug | {"modelAppType":"NUTS","brandType":"common","deviceId":"1281849e-8a12-1ea1-9377-a0cdf3f3ae2c:20","deviceType":401,"modelName":"**AWHP_019101_WW**","subModelNm":null,"sensorType":null,"alias":"Luft-Wasser-ärmepumpe","deviceCode":"AI05","networkType":"02","tftYn":"N","guideTypeYn":"Y","guideType":"TYPE5","pccModelYn":"N","autoOrderYn":"N","drServiceYn":"N","ssid":"","timezoneCode":"Europe/Berlin","timezoneCodeAlias":"Europe/Berlin","sdsGuide":"","newRegYn":"N","remoteControlType":null,"fareTarget":null,"area":"171218","sleep":null,"deviceState":"E","rmsClientId":null,"regDtUtc":"20240912204230000","regIndex":1,"blackboxYn":"Y","groupableYn":"Y","controllableYn":"Y","combinedProductYn":"N","masterYn":"Y","snapshot":"airState.tempState.airTempHeatMin":16,"airState.diagCode":0,"airState.tempState.waterTempCoolMin":5,"airState.tempState.airTempCoolMin":16,"mid":47995909,"airState.miscFuncState.awhpWaterControl":0,"airState.tempState.target":13,"airState.humidity.current":0,"airState.tempState.hotWaterTempMin":30,"airState.operation":1,"airState.tempState.waterTempHeatMax":65,"airState.tempState.airTempCoolMax":30,"timestamp":1728134684729,"airState.quality.PM10":0,"static": "deviceType" :"603", "countryCode":"DE"}, "airState.tempState.hotWaterCurrent":38,"airState.tempState.current":22,"airState.tempState.hotWaterTempMax":80,"airState.miscFuncState.awhpTempSwitch":1,"airState.miscFuncState.extraOp":0,"airState.tempState.hotWaterTarget":42,"airState.tempState.waterTempHeatMin":15,"airState.miscFuncState.powerHotWater":0,"airState.tempState.airTempHeatMax":30,"meta":{"allDeviceInfoUpdate": false,"messageId":"P48v8T8ISNC5t7Q5Qb24TA"},"airState.quality.PM1":0,"airState.tempState.waterTempCoolMax":27,"airState.miscFuncState.silentAWHP":0,"airState.quality.PM2":0,"online":true,"airState.miscFuncState.hotWater":1,"airState.opMode":3,"airState.tempState.outWaterCurrent":37,"airState.tempState.inWaterCurrent":36},"manufacture":null,"online":true,"platformType":"thinq2","homeDeviceOrder":-1,"roomDeviceOrder":-1,"ownershipYn":"Y","modelJsonVer":"17.2","modelJsonUri":"https://objectcontent.lgthinq.com/db176582-083a-4b32-947c-290144a7b60f?hdnts=exp=1776495302~hmac=3ed4896c04c9ebaff5699942401b46c8dac6d11e4a3b90c37ba5e1192710c34a","appModuleVer":"16.32","appModuleUri":"https://objectcontent.lgthinq.com/6c1a78d3-0404-4712-a5bc-2bc3d9e072b8?hdnts=exp=1745650858~hmac=cdff11328e2e89b5aee97c1ca005223d63d15d47f5d4fc07976284be9033797d","appRestartYn":"Y","appModuleSize":"13305760","langPackProductTypeVer":null,"langPackProductTypeUri":null,"langPackModelVer":null,"langPackModelUri":null,"roomId":"","fwInfoList":null,"modemInfo":null,"modemConfig":null,"existsEntryPopup":"N","fwVer":null,"modemVer":"clip_cgw_v1.0.030","subDeviceCount":0,"firebaseLogKey":null,"cardType":"Large","cardControl":"Combined","detailDeviceCode":null,"upgradableYn":"N","autoFwDownloadYn":"N","homeMovableYn":"Y","protocolVersion":null,"btAddress":null,"isTLV":null,"jsonList":null,"registrationFailCode":"","mdFotaYn":null,"demandType":null,"activatedContents":null,"modelControlValidateUri":null,"modelControlValidateVer":null,"matterYn":"N","groups":[]}
lg-thinq.0 | 2024-10-05 15:24:48.631 | debug | Get Device Model Info
```

Alle Versuche, Werte zu schreiben liefern die gleiche Fehlermeldung

**Versions:**  
 - Adapter version: 1.0.2 (von GIT)
 - iobroker 7.19
 - Node version: 21.6.2
 - Operating system: Windows; soll später auf Ubuntu laufen

**Additional context**

**Comment by Lucky-ESA** [comment]
Du musst den remote folder nehmen. Schau mal in die [Anleitung](https://github.com/TA2k/ioBroker.lg-thinq/blob/master/docs/de/README.md#ger%C3%A4t-401-klimanalage-thinq2)

Oder fehlt dieser bei dir?

**Comment by ArminMertes** [comment]
Hallo,

den Ordner gibt es. Allerdings sind dort die wesentlichen Objekte zur
Steuerung der WP, z.B. hotWaterTarget, nicht enthalten.
Hier ein Screenshot:
[image: image.png]
Daher meine Vermutung, daß die erfolglose Modellerkennung das eigentliche
Problem ist.

Grüsse
Armin

Am So., 6. Okt. 2024 um 21:14 Uhr schrieb Lucky-ESA <
***@***.***>:

**Comment by Lucky-ESA** [comment]
Das Thema hat ich schon öfter [hier ein Beispiel](https://github.com/TA2k/ioBroker.lg-thinq/issues/33#issuecomment-1859160566)
Hast du diesen Datenpunkt?
lg-thinq.0.xxx.remote.sendJSON

**Comment by ArminMertes** [comment]
Den Datenpunkt  lg-thinq.0.xxx.remote.sendJSON habe ich.
Ich habe auch schon versucht, dort Befehle abzusetzen
[{lg-thinq.0.1281849e-8a12-1ea1-9377-a0cdf3f3ae2c:20.snapshot.airState.tempState.hotWaterTarget:
42}]
und
[{airState.tempState.hotWaterTarget: 42}]
werden aber mit Syntax Error abgelehnt
sendData: SyntaxError: Expected property name or '}' in JSON at position 2
(line 1 column 3)


Am So., 6. Okt. 2024 um 21:40 Uhr schrieb Lucky-ESA <
***@***.***>:

**Comment by ArminMertes** [comment]
Bei diesem Format kommt keine Syntax-Fehlermeldung
{

"lg-thinq.0.1281849e-8a12-1ea1-9377-a0cdf3f3ae2c:20.snapshot.airState.tempState.hotWaterTarget":
"42"
}

Aber dann die 400er-Meldung; also wie bei der Änderung im Snapshort
[image: image.png]

Am So., 6. Okt. 2024 um 21:40 Uhr schrieb Lucky-ESA <
***@***.***>:

**Comment by Lucky-ESA** [comment]
Ich muss mal schauen wie der JSON ausehen könnte. Werde diesen aber erst morgen hier posten.

**Comment by ArminMertes** [comment]
Herzlichen Dank!

Am So., 6. Okt. 2024 um 22:16 Uhr schrieb Lucky-ESA <
***@***.***>:

**Comment by Lucky-ESA** [comment]
Dann versuche mal dein Glück. Leider kann ich hotWaterTarget laut deinen Template nicht zuordnen.
`
{"ctrlKey": "basicCtrl", "command": "Set", "dataKey": "airState.tempState.hotWaterTarget", "dataValue": 42}
`

**Comment by ArminMertes** [comment]
Hallo,

hat auf Anhieb funktioniert!
Ganz herzlichen Dank für die Unterstützung.

Schöne Grüße aus dem Saarland!
Armin

Am Mo., 7. Okt. 2024 um 19:18 Uhr schrieb Lucky-ESA <
***@***.***>:

**Comment by Lucky-ESA** [comment]
Bitte den Befehl absenden und dann die APP öffnen. Ist das Geräte dann gesperrt?

**Comment by ArminMertes** [comment]
Nein, klappt alles hervorragend.
Die Änderung wird innerhalb einer Sekunde sowohl in den Objekten als auch
in der APP angezeigt.
Ich kann weiterhin in der APP ändern; auch diese Updates gehen direkt durch.


Am Mo., 7. Okt. 2024 um 20:05 Uhr schrieb Lucky-ESA <
***@***.***>:

**Comment by Lucky-ESA** [comment]
OK, wie ich das in den Adapter bekomme kann ich derzeit nicht sagen.
Diese Meldung ist normal für dein Device: **deviceModel.type not found**

Wenn du den Link aus lg-thinq.0.xxx.modelJsonUri in den Browser eingibst, wird dein Template geladen. Dort sind noch Beispiele was noch bei dir gehen könnte.

**Comment by Lucky-ESA** [comment]
Added in next release
