### ISSUE TITLE
MODULE_NOT_FOUND error on startup

### ISSUE THREAD

**Issue by CrazyOrange** [TA2k/ioBroker.lg-thinq#59]
**Describe the bug**  
Adapter won't start

**To Reproduce**  
Start the adapter

**Expected behavior**  
Successful start of the adapter

**Screenshots & Logfiles**  

Source | Time | Level | Message
-- | -- | -- | --
host.iobroker10 | 2024-11-17 16:49:53.714 | info | Rebuild for adapter system.adapter.lg-thinq.0 not successful in 3 tries. Adapter will not be restarted again. Please execute "npm install --production" in adapter directory manually.
host.iobroker10 | 2024-11-17 16:49:53.714 | error | instance system.adapter.lg-thinq.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker10 | 2024-11-17 16:49:53.714 | error | Caught by controller[0]: Node.js v20.18.0
host.iobroker10 | 2024-11-17 16:49:53.714 | error | Caught by controller[0]: }
host.iobroker10 | 2024-11-17 16:49:53.714 | error | Caught by controller[0]: requireStack: [ '/opt/iobroker/node_modules/iobroker.lg-thinq/main.js' ]
host.iobroker10 | 2024-11-17 16:49:53.713 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.iobroker10 | 2024-11-17 16:49:53.713 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
host.iobroker10 | 2024-11-17 16:49:53.713 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1104:12)
host.iobroker10 | 2024-11-17 16:49:53.713 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1288:32)
host.iobroker10 | 2024-11-17 16:49:53.713 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
host.iobroker10 | 2024-11-17 16:49:53.713 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1469:14)
host.iobroker10 | 2024-11-17 16:49:53.712 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lg-thinq/main.js:23:15)
host.iobroker10 | 2024-11-17 16:49:53.712 | error | Caught by controller[0]: at require (node:internal/modules/helpers:179:18)
host.iobroker10 | 2024-11-17 16:49:53.712 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1311:19)
host.iobroker10 | 2024-11-17 16:49:53.712 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1051:27)
host.iobroker10 | 2024-11-17 16:49:53.712 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
host.iobroker10 | 2024-11-17 16:49:53.712 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.lg-thinq/main.js
host.iobroker10 | 2024-11-17 16:49:53.711 | error | Caught by controller[0]: Require stack:
host.iobroker10 | 2024-11-17 16:49:53.711 | error | Caught by controller[0]: Error: Cannot find module 'node-forge'
host.iobroker10 | 2024-11-17 16:49:53.711 | error | Caught by controller[0]: ^
host.iobroker10 | 2024-11-17 16:49:53.711 | error | Caught by controller[0]: throw err;
host.iobroker10 | 2024-11-17 16:49:53.711 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1228
host.iobroker10 | 2024-11-17 16:49:51.864 | info | instance system.adapter.lg-thinq.0 in version "1.0.2" started with pid 5609

**Versions:**  
 - Adapter version: 1.0.2
 - JS-Controller version: 6.0.11
 - Node version: v20.18.0
 - Operating system: linux (docker v10)

**Comment by Lucky-ESA** [comment]
Thank for your issues message, is on git fixed.
