### ISSUE TITLE
no device

### ISSUE THREAD

**Issue by krobipd** [TA2k/ioBroker.lg-thinq#6]
hallo und viele dank für deine Arbeit,

ich habe mir gerade deinen adapter installiert leider findet er keine devices.
ich habe momentan nur meinen Fernseher drin - in der app ist er gelistet.
es ist ein LG Oled 65b1 model (2021).

werden Fernseher nicht unterstützt? würde nämlich gerne probieren ob ich über Thinq mehr Optionen und Möglichkeiten bekommen als über den lg adapter.

**Comment by MedizinPumPer** [comment]
habe das gleiche problem seit dem letzten update, hoffe noch auf ein hotfix dazu.

**Comment by TA2k** [comment]
Ging es denn vorher?

**Comment by MedizinPumPer** [comment]
Ich hatte vorher eine Verbindung zu den devices, hab aber nicht mehr bisher damit gemacht gehabt.  

Mit freundlichen Grüßen aus der Heide,
Bastian Steinert

**Comment by fornax76-git** [comment]
Ich habe eine Waschmaschine und einen Fernseher drin.
Im Adapter sehe ich auch nur die Waschmaschine, was nicht so tragisch ist, weil ich dazu den LGWebOS Adapter nutze.
Es sieht aber so aus, dass das von LG irgendwie unterbunden wird.
Man kann in der APP Mitglieder einladen. Also die Geräte teilen. Wenn ich das mache, zeigt er mir an, dass nur die Waschmaschine geteilt wird.
Vermutlich wird hier irgendwie zwischen den devices unterschieden, was sich auch hier im Adapter zeigt,

**Comment by krobipd** [comment]
bin mir nicht sicher ob euer problem die selbe Ursache hat wie meines, was ich herausfinden konnte werden lg Fernseher nicht als device im Thinq unterstützt sondern eher so als steuerzentrale - Fernseher support ist als coming soon deklariert.

> ThinQ Connect currently supports 12 types of LG appliances, and will support LG TVs in the future.
https://thinq.developer.lge.com/en/cloud/about/service/ThinQ-Connect/

wann auch immer dieses soon ist, hab nur die Fernseher (mittlerweile 2) daher ist die restliche Integrierung für mich, und nur für mich, irrelevant. hatte einfach gehofft über die Thinq Integrierung tiefere Optionen für meine Fernseher zu haben als über den lg adapter.

mir ist nur aufgefallen das meine thinq meinen ersten Fernseher einfach mal so vergessen hatte - hab nach dem testen die app wieder deinstalliert. hab jetzt den zweiten Fernseher bekommen und wollte ihn dann dazu einbinden und siehe da ich hab gar kein gerät verbunden. irgendwie eigenartige Plattform, auch wenn ich die app nicht oder nicht mehr verwende sollten die geräte ja dennoch in der thinq platform bleiben. aber gut, soweit mein feedback zu der Thematik.

sorry das wusste ich beim erstellen des posting nicht - das die Fernseher gar nicht supported werden.
