### ISSUE TITLE
Warn Message in 1.05

### ISSUE THREAD

**Issue by wm20320** [TA2k/ioBroker.lg-thinq#62]
There is a Warn Message in the iobroker-Log:
`<html>
<body>

lg-thinq has an invalid jsonConfig: [{"instancePath":"/items/_headerAdapter","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/5/then/required","keyword":"required","params":{"missingProperty":"size"},"message":"must have required property 'size'"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"else"},"message":"must match \"else\" schema"}]
--

</body>
</html>`

lg-thinq 1.0.5
iobroker 7.4.3
node.js 20.18.1
host 7.0.4

Ignore, my own issue  or a bug?

thx Marcus

**Comment by Lucky-ESA** [comment]
is fixed in next Release (1.0.6)
