### ISSUE TITLE
Item description

### ISSUE THREAD

**Issue by Chris87-ux** [TA2k/ioBroker.lg-thinq#8]
Thank you very much for the Adapter, I was waiting for this one quiet long. 
I installed the adapter today and it was working immediately.
In addition, some values from my washing machine were updated, but for the most of the values (red circle) I do not know what this value mean or what it stand for. 
Is there any discerption available were the singe values can be translated?

Thanks again for your great work @TA2k .

![image](https://user-images.githubusercontent.com/55442459/165929396-e78c46fd-a464-479c-9298-840f7253b4c9.png)

**Comment by Lucky-ESA** [comment]
mapping lang templates
