### ISSUE TITLE
State \remote\expressMode only triggers Express Freeze

### ISSUE THREAD

**Issue by harryslapalot** [TA2k/ioBroker.lg-thinq#9]
Changing the state \remote\expressMode for my Fridge/Freezer only triggers Express Freeze. There should be two states for Express Freeze and Express Cool or at least both should be triggered.

LG GSXV90BSAE

**Comment by Technology89** [comment]
Can confirm  (LG GSXV90MCDE). Would be great if we can get an update for that

**Comment by Lucky-ESA** [comment]
Fix in 0.1.0

**Comment by harryslapalot** [comment]
Thanks for the effort! Unfortunately it still doesn't work for me. In the folder "remote" I only have an object called "expressMode". When I set it to 1, it only turn on Express Freeze. Am I missing something?
